version: "3"

services:
  db:
    image: postgres:13
    restart: always
    env_file: ./.env
    ports:
      - 5432:5432
    volumes:
      - ./docker/db/pgdata:/var/lib/postgresql/data
      - ./docker/db/initdb:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: ./docker/rails/dockerfile
    env_file: ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      - db
    stdin_open: true
    command: bundle exec rails s -p 8000 -b '0.0.0.0' -e production

  next:
    build:
      context: .
      dockerfile: ./docker/next/dockerfile
    env_file: ./.env
    working_dir: /app
    depends_on:
      - api
    tty: true
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command:  sh -c "yarn build && yarn start"

  nginx:
    image: nginx:1.13
    ports:
      - "80:80"
    env_file: ./.env
    build:
      context: .
      dockerfile: ./docker/nginx/dockerfile
      target: dev_stage
    depends_on:
      - next
    environment:
      TZ: ${TZ}

volumes:
  pgdata:
