FROM nginx:1.13 AS base_stage

ADD ./nginx/nginx.conf /etc/nginx/nginx.conf

FROM base_stage AS dev_stage
ADD ./nginx/dev.conf /etc/nginx/default.conf  

# FROM base_stage AS prod_stage
# ADD ./nginx/prod.conf /etc/nginx/default.conf