FROM node:15.0.1-alpine

ENV LANG=C.UTF-8 TZ=Asia/Tokyo
ENV NPM_CONFIG_LOGLEVEL warn

WORKDIR /app

COPY ./front/package.json ./front/yarn.lock ./

RUN yarn install --production --ignore-optional --ignore-scripts --pure-lockfile --non-interactive
RUN yarn add sharp --ignore-scripts=false

COPY ./front .

ENV HOST 0.0.0.0
EXPOSE 3000